export enum Permission {
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  ADD_ROLE_TO_USER = 'ADD_ROLE_TO_USER',
  REMOVE_ROLE_TO_USER = 'REMOVE_ROLE_TO_USER',
  ADD_PERMISSION_TO_ROLE = 'ADD_PERMISSION_TO_ROLE',
  REMOVE_PERMISSION_TO_ROLE = 'REMOVE_PERMISSION_TO_ROLE',
}
